### PR TITLE
Clean up skills seciton in the sk and threat sheet

### PR DESCRIPTION
**Pull request by Drental**
This is to adress any issues that might have come from premature changes done during the larger migration

This PR also removes many of the console.log statements that were used

### CODE REVIEW

**Comment by Algor0113** [comment]
@Drental  

Reviewed. 

Haven't looked at the code yet, but your modifications impacted the SKs as well. 

There are skills that cannot be rolled unskilled. In the past, there was a mechanic that forbade you to roll on these skills if you're not skilled in them. Unfortunately, I _can_ roll on these unskilled.

Those are:

* Air Vehicles
* Alteration
* Apportation
* Conjuration
* Divination
* Kinesis
* Language
* Lockpicking
* Medicine
* Precognition
* Reality
* Telepathy

Can you please ensure that this mechanic works again, please? 

On a further note, I'd like a tooltip shown on hovering skills, like in "click to add/remove the skill to the access list", what do you think?

**Comment by Drental** [comment]
added the tooltip but didn't localize it, because I'm lazy like that ^^;

**Comment by Algor0113** [comment]
image
Tooltip somehow is cut after the first word. Trying to get it, but if you're on it, don't hesitate :)

**Comment by Algor0113** [comment]
Never mind, got it

**Review by Algor0113 — APPROVED** [review]

**Pull request merged**
